version: '3.7'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./backend:/app
    env_file:
      - ./env/backend.dev.env
    depends_on:
      - database
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./frontend:/app
    env_file:
      - ./env/frontend.dev.env
    depends_on:
      - database
  nginx:
    image: nginx:alpine
    ports:
      - 8080:8080
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
  database:
    image: mongo:latest
    volumes:
      - database:/data/db
    env_file:
      - ./env/database.dev.env

volumes:
  database:
