version: '3.7'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./backend:/app
    env_file:
      - ./env/backend.dev.env
  database:
    image: mongo:latest
    volumes:
      - database:/data/db
    env_file:
      - ./env/database.dev.env

volumes:
  database:
