version: '3.7'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      target: prod
    env_file:
      - ./env/backend.prod.env
    depends_on:
      - database
    restart: unless-stopped
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: prod
    volumes:
      - frontend:/app/.next
    env_file:
      - ./env/frontend.prod.env
    depends_on:
      - database
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    ports:
      - 8080:8080
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
  database:
    image: mongo:latest
    volumes:
      - database_prod:/data/db
    env_file:
      - ./env/database.prod.env
    restart: unless-stopped

volumes:
  frontend:
  database_prod:
